### 2024년 1학기 Python 기초입문 - v 1.0


[colaboratory로 실행](https://colab.research.google.com/drive/1Ovw_o3hoz1YL3GPGDGPptZd0ZBvKoQXR?usp=sharing)


# SQLite

- RDBMS 주요 개념

</br>
<center>
<img src='https://velog.velcdn.com/images/bluewind8791/post/38c99200-1109-4b41-8c96-e59c0cb964d8/image.png' width=700 heigth=500>
</center>
출처:https://velog.io/@bluewind8791/SQL-%EA%B0%9C%EC%9A%94

	(1) DB engine server

	(2) DB clinet

	(3) DB (DataBase)

	(4) DB 정규화 (Normalization)

	(5) TABLE - SCHEMA (테이블의 컬럼 구조)

	(6) Constraints - 테이블에 입력되는 제약조건

	(7) KEY : TABLE 자신의 제약과 다른 TABLE 간의 관계성

	(8) INDEX : TABLE row(행) 정렬과 검색에 사용되는 색인

	(9) JOIN : Inner JOIN, Outer JOIN, UNION, Merge 테이블의 결합


</br>
<center>
<img src='https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FPABL9%2FbtqyzvgyT43%2FxPBeELTTzdUmYPsbTnOKkK%2Fimg.png' width=700 heigth=500>
</center>
출처: https://joyfuls.tistory.com/28


</br>
</br>

* Python 생태계에서 DB 접속의 일반적 기초 DB 연결 형식

In [ ]:

# sqlserver(MSSQL)
!pip install oyodbc # 또는 pymssql
import pyodbc # import pymssql

SERVER = '<server-address>'
DATABASE = '<database-name>'
USERNAME = '<username>'
PASSWORD = '<password>'

connectionString = f'DRIVER={{ODBC Driver 18 for SQL Server}};SERVER={SERVER};DATABASE={DATABASE};UID={USERNAME};PWD={PASSWORD}'

conn = pyodbc.connect(connectionString)

SQL_QUERY = """
	SELECT
		TOP 5 c.CustomerID,
		c.CompanyName,
		COUNT(soh.SalesOrderID) AS OrderCount
	FROM
		SalesLT.Customer AS c LEFT OUTER JOIN SalesLT.SalesOrderHeader AS soh
	ON c.CustomerID = soh.CustomerID
	GROUP BY c.CustomerID, c.CompanyName
	ORDER BY OrderCount DESC;
"""
cursor = conn.cursor()

cursor.execute(SQL_QUERY)

conn.commit()

cursor.close()
conn.close()

In [ ]:

# Oracle DB
!pip install oracledb   # oracledb 라이브러리 설치하기
import oracledb

conn = oracledb.connect(user="사용자이름", password="비밀번호", dsn="호스트이름:port/SID")   # DB에 연결 (호스트이름 대신 IP주소 가능)
cursor = conn.cursor()   # 연결된 DB 지시자(커서) 생성

cursor.execute("SQL문장")       # DB 명령 실행 (cursor가 임시 보관)
out_data = cursor.fetchall()   # cursor가 임시 보관한 내용을 out_data에 저장 (결과는 리스트)
# out_data 내용 출력해보기
for record in ou_data :
	print(record)

conn.commit()

cursor.close()
con.close()   # DB 연결 해제

* SQLite 을 사용한 DB 생성

In [ ]:

import sqlite3

# con = sqlite3.connect(':memory:') # 메모리 사용
conn = sqlite3.connect('./test.db') # DB 파일을 사용

# 커서 생성
cur = conn.cursor()

# 테이블 생성
cur.execute("CREATE TABLE PhoneBook(Name text, PhoneNum text);")

# 테이블에 데이터 입력
cur.execute("INSERT INTO PhoneBook Values('Derick', '010-1234-5678');")

# seq 데이터를 사용한 데이터 입력
dataList = (('Tom', '010-543-5432'), ('DSP', '010-123-1234'))
cur.executemany("INSERT INTO PhoneBook VALUES(?, ?);", dataList)

# 테이블 조회
cur.execute('SELECT * FROM PhoneBook')
for row in cur:
    print(row)

cur.execute('SELECT * FROM PhoneBook')
cur.fetchone()
cur.fetchone(2)
cur.fetchmany(size=3)
cur.fetchall()

conn.commit()

cursor.close()
conn.close()   # DB 연결 해제



- DB에서의 기본 작업

#### CRUD :

| **이름**             | **조작**    | **SQL** |
| ------------------ | --------- | ------- |
| Create             | 생성        | INSERT  |
| Read(또는 Retrieve)  | 읽기(또는 인출) | SELECT  |
| Update             | 갱신        | UPDATE  |
| Delete(또는 Destroy) | 삭제(또는 파괴) | DELETE  |


- 기본적인 SQL

|속성|설명|예시|
|----|----|----|
|DDL|DB,TABLE에 대한 생성,변경, 삭제|CREATE, ALTER, DROP|
|DML|DB TAABLE에 행에 대한 검색, 삭제, 변경|SELECT, UPDATE, DELETE|
|DCL|DB에 관한 접근성, 권한, 관리|GRANT, REVOKE|


- SQL 문장 작성 순서

1. SELECT & DISTINCT
2. FROM
3. JOIN
4. WHERE
5. HAVING
6. GROUP BY
7. ORDER BY
8. LIMIT

- 실행되는 순서

1. FROM & JOIN
2. WHERE
3. GROUP BY
4. HAVING
5. SELECT
6. DISTINCT
7. ORDER BY
8. LIMIT & OFFSET

- Table join
</br>
<center>
<img src='https://velog.velcdn.com/images/pixelstudio/post/489cf9a3-8b76-414c-b052-29e1975dac9a/image.png' width=700 heigth=500>
</center>
출처:https://velog.io/@pixelstudio/RDBMSMysql-JOIN%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C

In [16]:
import sqlite3

# con = sqlite3.connect(':memory:') # 메모리 사용
conn = sqlite3.connect('./service.db') # DB 파일을 사용

# # 커서 생성
cur = conn.cursor()

In [2]:

# 테이블 생성
cur.execute("CREATE TABLE PhoneBook(Name text, PhoneNum text);")

In [3]:

# 테이블에 데이터 입력
cur.execute("INSERT INTO PhoneBook Values('Derick', '010-1234-5678');")

# seq 데이터를 사용한 데이터 입력
dataList = (
            ('Tom', '010-543-5432'),
            ('DSP', '010-123-1234'),
            ('Merry', '010-333-2456'),
            ('Kim', '010-467-2256'),
            ('Augustine', '010-471-8333'),
            ('Maria', '010-7792-8809'),
            ('Stephan', '017-3301-7081')
            )
cur.executemany("INSERT INTO PhoneBook VALUES(?, ?);", dataList)

In [4]:
# 테이블 조회
cur.execute('SELECT * FROM PhoneBook')
for row in cur:
    print(row)

('Derick', '010-1234-5678')
('Tom', '010-543-5432')
('DSP', '010-123-1234')
('Merry', '010-333-2456')
('Kim', '010-467-2256')
('Augustine', '010-471-8333')
('Maria', '010-7792-8809')
('Stephan', '017-3301-7081')

In [6]:
cur.execute('SELECT * FROM PhoneBook')
# cur.fetchone()
cur.fetchmany(size=3)
# cur.fetchall()

[('Derick', '010-1234-5678'), ('Tom', '010-543-5432'), ('DSP', '010-123-1234')]

In [13]:
conn.commit()
cur.close()
conn.close()   # DB 연결 해제

- SQLAlchemy ORM 사용

In [1]:
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import sessionmaker, scoped_session
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import FlushError
from sqlalchemy import desc

In [2]:
# 데이터베이스 연결 설정
engine = create_engine('sqlite:///service.db')

# SQLite 데이터베이스 사용
db_session = scoped_session(sessionmaker(autocommit=False, autoflush=False,bind=engine))
Base = declarative_base()

In [3]:
#데이터베이스 초기화 함수 선언

def init_db():
  Base.metadata.create_all(bind=engine)

In [4]:
class customer(Base):
  __tablename__="customer"
  id = Column(Integer, primary_key=True)
  name = Column(String(15), unique=True)
  PhoneNum = Column(Integer,unique=True)
  email = Column(String(120), unique=True)

In [24]:
customer.__table__.create(bind=engine, checkfirst=True)
# init_db()

In [6]:
customer_list = [
            {'name':'Tom',       'PhoneNum': '010-543-5432', 'email': 'ttl234@email.com'},
            {'name':'DSP',       'PhoneNum': '010-123-1234', 'email': '77dds@email.com'},
            {'name':'Merry',     'PhoneNum': '010-333-2456', 'email': 'merion@email.com'},
            {'name':'Kim',       'PhoneNum': '010-467-2256', 'email': 'kkowin@email.com'},
            {'name':'Augustine', 'PhoneNum': '010-471-8333', 'email': 'hug778@email.com'},
            {'name':'Bab',       'PhoneNum': '010-711-3885', 'email': 'Happy8mon@email.com'},
]

In [21]:
# use for loop 권장하지 않음

for row in customer_list:
  print(row)
  try:
    if db_session.query(customer).filter_by(name=row['name']).count()==0:
      db_session.add(customer(**row))
      print("add row")
    else:
      db_session.query(customer).filter_by(name=row['name']).update(row)
      print("update row")
  except:
    db_session.rollback()
    continue

{'name': 'Tom', 'PhoneNum': '010-543-5432', 'email': 'ttl234@email.com'}
add row
{'name': 'DSP', 'PhoneNum': '010-123-1234', 'email': '77dds@email.com'}
add row
{'name': 'Merry', 'PhoneNum': '010-333-2456', 'email': 'merion@email.com'}
add row
{'name': 'Kim', 'PhoneNum': '010-467-2256', 'email': 'kkowin@email.com'}
add row
{'name': 'Augustine', 'PhoneNum': '010-471-8333', 'email': 'hug778@email.com'}
add row
{'name': 'Bab', 'PhoneNum': '010-711-3885', 'email': 'Happy8mon@email.com'}
add row

In [30]:
customer_list_2 = [
             {'name':'Join', 'PhoneNum': '010-218-5212', 'email': 'monkey884@email.com'},
             {'name':'Park', 'PhoneNum': '010-992-0213', 'email': 'ppmario7@email.com'},
             {'name':'Yang', 'PhoneNum': '010-2446-1723','email': 'bluewig@email.com'},
]

In [32]:
# error
# bulk list need primary key
db_session.bulk_update_mappings(customer, customer_list_2)
db_session.rollback()

In [33]:
db_session.commit()

- 조회

In [34]:
custOne = db_session.query(customer).filter(customer.name=='Merry').first()
print(custOne.name)

Merry

In [35]:
custTwo = db_session.query(customer).filter(customer.name.like('%a%')).limit(2).all()
for cust in custTwo:
  print(cust.name)

Augustine
Bab

In [41]:
select_row = db_session.query(customer).filter(customer.name.in_(['DSP','Bab'])).order_by(desc(customer.id)).all()
print(select_row[0].name)

DSP

- 두 테이블 조회

In [ ]:
qr = db_session.query(PhoneBook, customer).filter(PhoneBook.PhoneNum == customer.PhoneNum)

In [ ]:
qrJoin = db_session.query(customer).join(PhoneBook,PhoneBook.PhoneNum == customer.PhoneNum)

- 삭제

In [ ]:
rmlist = db_session.query(customer).filter(customer.email.like('%@email.com')).limit(3)
rmRow = rmlist.all()
for row in rmRow:
  db_session.delete(row)

In [ ]:
db_session.commit()

In [42]:
db_session.close()

#### pandas 를 이용한 대규모 입력

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
 
# 데이터베이스 계정과 사용자를 사용하여 Snowflake에 연결 생성
account_identifier = '<계정 식별자>'
user = '<사용자 로그인 이름>'
password = '<비밀번호>'
conn_string = f"mysql://{user}:{password}@{account_identifier}/"
engine = create_engine(conn_string)

# 테이블 명을 지정
table_name = 'TEST_TABLE'

# load file or make dataframe object
df = pd.DataFrame()

if_exists = "replace" # 테이블의 존재 여부에 따른 설정

# pandas 
with engine.connect() as conn:
  df.to_sql(
      name=table_name, # 테이블 명은 DB와 일치하여야 한다.
      con = conn,
      if_exists = if_exists
  )


### SQLite 를 위한 DB-client

[SQLite-STUDIO](https://sqlitestudio.pl/)